package com.itp.DigLib.api.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.itp.DigLib.api.model.Book;
import com.itp.DigLib.db.BookRepository;

@Controller // This means that this class is a Controller
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private BookRepository bookRepo;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewBook (
    @RequestParam String title,
    @RequestParam String author,
    @RequestParam String genre,
    @RequestParam String isbn,
    @RequestParam int year

  ) {
    Book book = new Book();
    book.setTitle(title);
    book.setAuthor(author);
    book.setGenre(genre);
    book.setIsbn(isbn);
    book.setYear(year);
    bookRepo.save(book);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Book> getAllBooks() {
    // This returns a JSON or XML with the users
    return bookRepo.findAll();
  }
}